Allow docker applications to run in PCF

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -47,18 +47,18 @@ if [ -f ${manifest} ]; then
 		echo "Application [$bwBundleAppName] is not supported in TIBCO BusinessWorks Container Edition. Convert this application to TIBCO BusinessWorks Container Edition using TIBCO BusinessWorks Container Edition Studio. Refer Conversion Guide for more details."
 		exit 1
 	fi
-	bwceTargetHeaderStr=`grep -E $bwceTarget ${manifest}`
-	res=$?
-	if [ ${res} -eq 0 ]; then
-		bwceTargetStr=`echo "$bwceTargetHeaderStr" | grep -E 'cf'`
-		res2=$?
-		if [ ${res2} -eq 0 ]; then
-			echo ""
-		else
-			echo "Application [$bwBundleAppName] is not supported on the CloudFoundry platform and cannot be started. You should convert this application using TIBCO BusinessWorks Container Edition Studio. Refer Application Development guide for more details."
-			exit 1
-		fi
-	fi
+	#bwceTargetHeaderStr=`grep -E $bwceTarget ${manifest}`
+	#res=$?
+	#if [ ${res} -eq 0 ]; then
+		#bwceTargetStr=`echo "$bwceTargetHeaderStr" | grep -E 'cf'`
+		#res2=$?
+		#if [ ${res2} -eq 0 ]; then
+			#echo ""
+		#else
+			#echo "Application [$bwBundleAppName] is not supported on the CloudFoundry platform and cannot be started. You should convert this application using TIBCO BusinessWorks Container Edition Studio. Refer Application Development guide for more details."
+			#exit 1
+		#fi
+	#fi
 fi
 arr=$(echo $bwAppProfileStr | tr "/" "\n")
 
